/*---------------------------------------------------------- 
MASV: 46.01.104.005
HO TEN: Phạm Nguyệt Anh
LAB: 03 
NGAY:  22/03/2023
----------------------------------------------------------*/ 
CREATE DATABASE QLSV
GO

USE QLSV
GO

CREATE TABLE SINHVIEN (
	MASV VARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL
)
GO

CREATE TABLE NHANVIEN (
	MANV VARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY(MAX),
	TENDN NVARCHAR(100) NOT NULL,	
	MATKHAU VARBINARY(MAX) NOT NULL,
	PUBKEY VARCHAR(20)
)
GO

CREATE TABLE LOP (
	MALOP VARCHAR(20) PRIMARY KEY,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20)
)
GO
CREATE TABLE HOCPHAN(
	MAHP VARCHAR(20) PRIMARY KEY,
	TENHP NVARCHAR(100),
	SOTC INT
)

CREATE TABLE BANGDIEM(
	MASV VARCHAR(20),
	MAHP VARCHAR(20),
	DIEMTHI VARBINARY(MAX)
	FOREIGN KEY (MASV) REFERENCES SINHVIEN (MASV), 
	FOREIGN KEY (MAHP) REFERENCES HOCPHAN (MAHP) 
)
/* Stored dùng để thêm mới dữ liệu (Insert) vào table SINHVIEN, 
trong đó thuộc tính MATKHAU được mã hóa (HASH) sử dụng MD5*/
ALTER PROC SP_INS_SINHVIEN 
	@MASV VARCHAR(20) ,
	@HOTEN NVARCHAR(100), 
	@NGAYSINH DATETIME,
	@DIACHI NVARCHAR(200),
	@MALOP VARCHAR(20),
	@TENDN NVARCHAR(100), 
	@MATKHAU VARCHAR(MAX) 
AS
BEGIN   
	DECLARE @md5 VARBINARY(MAX)
	SET @md5 = CONVERT(VARBINARY(MAX), HASHBYTES('MD5', @MATKHAU), 2)

	INSERT INTO SINHVIEN(MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, MATKHAU) 
	VALUES(@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, @md5)
END

SELECT * FROM SINHVIEN
EXEC SP_INS_SINHVIEN 'SV03', 'ANH3', '1/1/1990', '280 AN DUONG VUONG', 'CNTT-K46', 'ANH3', '123456'

/*Stored dùng để thêm mới dữ liệu (Insert) vào table NHANVIEN, trong đó thuộc tính
MATKHAU được mã hóa (HASH) sử dụng SHA1 và thuộc tính LUONG sẽ được mã
hóa sử dụng thuật toán AES 256, với khóa mã hóa là mã số của sinh viên thực hiện bài
Lab này.*/
CREATE SYMMETRIC KEY SK01
WITH 
	ALGORITHM = AES_256
	ENCRYPTION BY PASSWORD  = '46.01.104.005'
GO
 
CREATE PROC SP_INS_NHANVIEN
	@MANV VARCHAR(20),
	@HOTEN NVARCHAR(100),
	@EMAIL VARCHAR(20),
	@LUONG VARCHAR(MAX),
	@TENDN NVARCHAR(100),
	@MATKHAU VARCHAR(MAX)
AS
BEGIN
	DECLARE @MATKHAUBINARY VARBINARY(MAX)
	SET @MATKHAUBINARY = CONVERT(VARBINARY(MAX), HASHBYTES('SHA1', @MATKHAU), 2)

	SET NOCOUNT ON;
	 
	OPEN SYMMETRIC KEY SK01
	DECRYPTION BY PASSWORD = '46.01.104.005' 

	INSERT INTO NHANVIEN(MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU) 
	VALUES(@MANV, @HOTEN, @EMAIL, ENCRYPTBYKEY(KEY_GUID('SK01'), CONVERT(VARBINARY(MAX), @LUONG)) , @TENDN, @MATKHAUBINARY)

	CLOSE SYMMETRIC KEY SK01
END
GO

select * from NHANVIEN  
EXEC SP_INS_NHANVIEN 'NV02', 'ANH2', 'NVA@', '6000000', 'NVANH2', 'abcd12' 
--UPDATE NHANVIEN SET TENDN = 'PNA2' WHERE MANV = 'NV02'
/*Stored dùng để truy vấn dữ liệu nhân viên (NHANVIEN)*/
go
CREATE PROC SP_SEL_NHANVIEN
AS
BEGIN
	OPEN SYMMETRIC KEY SK01
	DECRYPTION BY PASSWORD = '46.01.104.005'

	SELECT MANV, HOTEN, EMAIL, CONVERT(VARCHAR(MAX), DECRYPTBYKEY(LUONG)) AS LUONGCB
	FROM NHANVIEN

	CLOSE SYMMETRIC KEY SK01
END

EXEC SP_SEL_NHANVIEN

